### PR TITLE
Add Price resource

### PR DESCRIPTION
**Pull request by stevenbarragan**

### CODE REVIEW

**Comment by allolex** [comment]
@stevenbarragan I've fixed the new repo and made it public over here: 

https://github.com/allolex/nacre

**Comment by stevenbarragan** [comment]
Thanks @allolex we're going to take a look of it.

**Comment by allolex** [comment]
Cool. 

Also, if you submit a PR, please include tests and rebase/squash your commits so the commit history is relatively clean. I can pair with you on that if you need help. :)

**Comment by stevenbarragan** [comment]
closing this due repo deprecation

**Pull request closed without merging**
